Refactor codes: modularize methods, rearrange global variables

diff --git a/config-wifi b/config-wifi
--- a/config-wifi
+++ b/config-wifi
@@ -1,115 +1,126 @@
 #!/bin/bash
 MODE=$1
 
+INTERFACE="wlan0"
+
+WIFI_INTERFACE_FILE=/etc/network/interfaces
+
+HIDDEN=0
+
+WIFI_CREDENTIAL="network={
+  ssid=\"$SSID\"
+  psk=\"$PASSWORD\"
+  scan_ssid=$HIDDEN\\n}"
+
+WIFI_CONFIG_FILE_URL=/etc/wpa_supplicant/wpa_supplicant.conf
+
+# IP for the checking server
+SERVER=8.8.8.8
+
 # Initialize WiFi
 init () {
-    echo "Initialize WiFi interface"
-    INTERFACE="wlan0"
-    WIFI_INTERFACE_FILE=/etc/network/interfaces
+  echo "Initialize WiFi interface"
+  
+  grep ${INTERFACE} $WIFI_INTERFACE_FILE > /dev/null
 
-    grep ${INTERFACE} $WIFI_INTERFACE_FILE > /dev/null
+  # If returns 0, it means have errors
+  if [ $? != 0 ]
+  then
+    # Add wireless interface network into the configuration file.
+    echo "auto lo" >> $WIFI_INTERFACE_FILE
+    echo >> $WIFI_INTERFACE_FILE
+    echo "iface lo inet loopback" >> $WIFI_INTERFACE_FILE
+    echo "iface eth0 inet dhcp" >> $WIFI_INTERFACE_FILE
+    echo >> $WIFI_INTERFACE_FILE
+    echo "allow-hotplug wlan0" >> $WIFI_INTERFACE_FILE
+    echo "auto wlan0" >> $WIFI_INTERFACE_FILE
+    echo "iface wlan0 inet dhcp" >> $WIFI_INTERFACE_FILE
+    echo "wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf" >> $WIFI_INTERFACE_FILE
+    echo >> $WIFI_INTERFACE_FILE
+    echo "iface default inet dhcp" >> $WIFI_INTERFACE_FILE
 
-    # If returns 0, it means have errors
-    if [ $? != 0 ]
+    ifconfig wlan0 up
+
+    if [ $? == 0 ]
     then
-        # Add wireless interface network into the configuration file.
-        echo "auto lo" >> $WIFI_INTERFACE_FILE
-        echo >> $WIFI_INTERFACE_FILE
-        echo "iface lo inet loopback" >> $WIFI_INTERFACE_FILE
-        echo "iface eth0 inet dhcp" >> $WIFI_INTERFACE_FILE
-        echo >> $WIFI_INTERFACE_FILE
-        echo "allow-hotplug wlan0" >> $WIFI_INTERFACE_FILE
-        echo "auto wlan0" >> $WIFI_INTERFACE_FILE
-        echo "iface wlan0 inet dhcp" >> $WIFI_INTERFACE_FILE
-        echo "wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf" >> $WIFI_INTERFACE_FILE
-        echo >> $WIFI_INTERFACE_FILE
-        echo "iface default inet dhcp" >> $WIFI_INTERFACE_FILE
-
-        ifconfig wlan0 up
-
-        if [ $? == 0 ]
-        then
-            echo "Configure network interface"
-        else
-            echo
-            echo "Failed to configure network."
-            exit 1
-        fi
+      echo "Configure network interface"
+    else
+      echo
+      echo "Failed to configure network."
+      exit 1
     fi
+  fi
 
-    echo "Complete successfully."
+  echo "Complete successfully."
 }
 
 # Setup wifi
 setup () {
-    # Ask user to input information
-    echo "Enter your WiFi configuration"
-    read -p 'Network name (SSID): ' SSID
-    read -sp 'Password: ' PASSWORD
-    echo
-    read -p "Is it a hidden network? [y/n]" RESPONSE
+  # Ask user to input information
+  echo "Enter your WiFi configuration"
+  read -p 'Network name (SSID): ' SSID
+  read -sp 'Password: ' PASSWORD
+  echo
+  read -p "Is it a hidden network? [y/n]" RESPONSE
+
+  if [ "$RESPONSE" = "y" ]; then
+    # Hidden network
+    HIDDEN=1
+  else
+    # Discoverable network
     HIDDEN=0
-    if [ "$RESPONSE" = "y" ]; then
-        # Hidden network
-        HIDDEN=1
-    else
-        # Discoverable network
-        HIDDEN=0
-    fi
+  fi
 
-    WIFI_CREDENTIAL="network={
-    ssid=\"$SSID\"
-    psk=\"$PASSWORD\"
-    scan_ssid=$HIDDEN\\n}"
+  # Put configuration into network config file.
+  # Raspberry Pi will read these configuration data to connect to the network.
+  echo "country=JP" > $WIFI_CONFIG_FILE_URL
+  echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev" >> $WIFI_CONFIG_FILE_URL
+  echo "update_config=1" >> /$WIFI_CONFIG_FILE_URL
+  echo "ap_scan=1" >> $WIFI_CONFIG_FILE_URL
+  echo >> $WIFI_CONFIG_FILE_URL
 
-    WIFI_CONFIG_FILE_URL=/etc/wpa_supplicant/wpa_supplicant.conf
-    # Put configuration into network config file.
-    # Raspberry Pi will read these configuration data to connect to the network.
-    echo "country=JP" > $WIFI_CONFIG_FILE_URL
-    echo "ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev" >> $WIFI_CONFIG_FILE_URL
-    echo "update_config=1" >> /$WIFI_CONFIG_FILE_URL
-    echo "ap_scan=1" >> $WIFI_CONFIG_FILE_URL
-    echo >> $WIFI_CONFIG_FILE_URL
+  echo -e "$WIFI_CREDENTIAL" >> $WIFI_CONFIG_FILE_URL
 
-    echo -e "$WIFI_CREDENTIAL" >> $WIFI_CONFIG_FILE_URL
-
-    if [ $? != 0 ]; then
-        echo "Failed to setup. Try it again."
-    else
-        echo "Connect successfully."
-    fi
+  if [ $? != 0 ]; then
+    echo "Failed to setup. Try it again."
+  else
+    echo "Connect successfully."
+  fi
 }
 
 # Restart WiFi
 restart () {
-    echo "Checking network ..."
-    # IP for the checking server
-    SERVER=8.8.8.8
-
-    ping -c2 ${SERVER} > /dev/null
-    
-    # If the return code from ping ($?) is not 0 (means there was an error)
-    if [ $? != 0 ]; then
-        echo "Restarting WiFi connection ... "
-        # Restart the wireless interface
-        ifconfig wlan0 down
-        ifconfig wlan0 up
-        echo "WiFi is restarted successfully."
-    else
-        echo "There is an error occurred."
-        echo "Can not restart WiFi connection."
-    fi
+  echo "Checking network ..."
+  
+  ping -c2 ${SERVER} > /dev/null
+  
+  # If the return code from ping ($?) is not 0 (means there was an error)
+  if [ $? != 0 ]; then
+    echo "Restarting WiFi connection ... "
+    # Restart the wireless interface
+    ifconfig wlan0 down
+    ifconfig wlan0 up
+    echo "WiFi is restarted successfully."
+  else
+    echo "There is an error occurred."
+    echo "Can not restart WiFi connection."
+  fi
 }
 
-if [ "$MODE" = "init" ]; then
+main()
+{
+  if [ "$MODE" = "init" ]; then
     init
-elif [ "$MODE" = "setup" ]; then
+  elif [ "$MODE" = "setup" ]; then
     setup
-elif [ "$MODE" = "restart" ]; then
+  elif [ "$MODE" = "restart" ]; then
     restart
-else 
+  else 
     echo -e "Can not identify command. 
     \t- Use 'init' to initialize WiFi configuration.
     \t- Use 'setup' to set up new WiFi configuration.
     \t- Use 'restart' to restart WiFi connection."
-fi
+  fi
+}
+
+main
diff --git a/install-jetty b/install-jetty
--- a/install-jetty
+++ b/install-jetty
@@ -1,85 +1,91 @@
 #!/bin/bash
 
-# Init option variables
-while getopts l: option
-do
- case "${option}"
- in
- l) URL=${OPTARG};;
- esac
-done
+JETTY_DOWNLOAD_URL=${URL:=http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.8.v20171121/jetty-distribution-9.4.8.v20171121.zip}
+JETTY_DESTINATION_FILE=/opt/jetty/jetty.zip
 
-# Check java version
-echo "Checking Java availability ..."
-javac -version
-if [ $? != 0 ]
-then
+main()
+{
+  # Init option variables
+  while getopts l: option
+  do
+  case "${option}"
+  in
+  l) URL=${OPTARG};;
+  esac
+  done
+
+  # Check java version
+  echo "Checking Java availability ..."
+  javac -version
+  if [ $? != 0 ]
+  then
     # Java install
     echo "Java is not installed yet."
     echo "Installing Java ..."
     apt-get update && sudo apt-get install oracle-java8-jdk
     if [ $? != 0 ]; then                   
-        echo "Failed to Java 8: $?"
-        exit 1
+      echo "Failed to Java 8: $?"
+      exit 1
     fi
-fi 
+  fi 
 
-# Download Jetty
-echo "Start downloading Jetty ..."
-JETTY_DOWNLOAD_URL=${URL:=http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.8.v20171121/jetty-distribution-9.4.8.v20171121.zip}
-JETTY_DESTINATION_FILE=/opt/jetty/jetty.zip
-mkdir /opt/jetty
-curl "$JETTY_DOWNLOAD_URL" -o $JETTY_DESTINATION_FILE
+  # Download Jetty
+  echo "Start downloading Jetty ..."
+  mkdir /opt/jetty
+  curl "$JETTY_DOWNLOAD_URL" -o $JETTY_DESTINATION_FILE
 
-if [ -f "$JETTY_DESTINATION_FILE" ]
-then
+  if [ -f "$JETTY_DESTINATION_FILE" ]
+  then
     echo "Complete downloading."
-else
+  else
     echo
     echo "Failed to download Jetty."
     exit 1
-fi
+  fi
 
-# Extract Jetty file archive
-cd /opt/jetty
-unzip jetty.zip
-mv jetty-distribution-*/ runtime
-rm jetty.zip
+  # Extract Jetty file archive
+  cd /opt/jetty
+  unzip jetty.zip
+  mv jetty-distribution-*/ runtime
+  rm jetty.zip
 
-# Setup Jetty as a Linux service
-cp /opt/jetty/runtime/bin/jetty.sh /etc/init.d/jetty
-echo JETTY_HOME=/opt/jetty/runtime > /etc/default/jetty
-# Test if it is set up successfully
-service jetty start
+  # Setup Jetty as a Linux service
+  cp /opt/jetty/runtime/bin/jetty.sh /etc/init.d/jetty
+  echo JETTY_HOME=/opt/jetty/runtime > /etc/default/jetty
+  # Test if it is set up successfully
+  service jetty start
 
-if [ $? == 0 ]
-then
+  if [ $? == 0 ]
+  then
     # Succeed. Stop service
     service jetty stop
-else
+  else
     # Failed
     echo "Failed to set Jetty as a service"
     exit 1
-fi
+  fi
 
-# Automatically start Jetty
-update-rc.d jetty defaults
+  # Automatically start Jetty
+  update-rc.d jetty defaults
 
-# Configure Jetty to run with a 'jetty' user
-mkdir -p /opt/jetty/web/bbq
-mkdir -p /opt/jetty/temp
-useradd --user-group --shell /bin/false --home-dir /opt/jetty/temp jetty
+  # Configure Jetty to run with a 'jetty' user
+  mkdir -p /opt/jetty/web/bbq
+  mkdir -p /opt/jetty/temp
+  useradd --user-group --shell /bin/false --home-dir /opt/jetty/temp jetty
 
-# Setup Jetty base configuration
-cd /opt/jetty/web/bbq
-java -jar /opt/jetty/runtime/start.jar --add-to-start=deploy,http,console-capture
+  # Setup Jetty base configuration
+  cd /opt/jetty/web/bbq
+  java -jar /opt/jetty/runtime/start.jar --add-to-start=deploy,http,console-capture
 
-# Wrap configuration of Jetty service
-chown -R jetty:jetty /opt/jetty
-echo "JETTY_HOME=/opt/jetty/runtime" > /etc/default/jetty
-echo "JETTY_BASE=/opt/jetty/web/bbq" >> /etc/default/jetty
-echo "TMPDIR=/opt/jetty/temp" >> /etc/default/jetty
+  # Wrap configuration of Jetty service
+  chown -R jetty:jetty /opt/jetty
+  echo "JETTY_HOME=/opt/jetty/runtime" > /etc/default/jetty
+  echo "JETTY_BASE=/opt/jetty/web/bbq" >> /etc/default/jetty
+  echo "TMPDIR=/opt/jetty/temp" >> /etc/default/jetty
 
-# Now Jetty run on default port 8080
-echo "Successfully! Jetty is now running at: http://localhost:8080"
-exit 0
+  # Now Jetty run on default port 8080
+  echo "Successfully! Jetty is now running at: http://localhost:8080"
+  exit 0
+}
+
+main
