Fix option arguments in scripts

diff --git a/install-app b/install-app
--- a/install-app
+++ b/install-app
@@ -1,23 +1,35 @@
 #!/bin/bash
 
-# Read app url
-APP_FILE_URL=${URL:=https://s3-ap-northeast-1.amazonaws.com/aromajoin-downloads/software/aroma-http-controller/sample.war}
-
-APP_FILE=${NAME:=sample.war}
-
-DESTINATION_FILE=$HOME/$APP_FILE
+# Handle option arguments
+while getopts ":l:n:" opt; do
+  case $opt in
+    l)
+      URL=$OPTARG
+      echo "Download link: $URL" >&2
+      ;;
+    n)
+      NAME=$OPTARG
+      echo "File: $NAME" >&2
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
 
 main()
 {
-  # Init option variables
-  while getopts l:n: option
-  do
-  case "${option}"
-  in
-  l) URL=${OPTARG};;
-  n) NAME=${OPTARG};;
-  esac
-  done
+  # Read app url
+  APP_FILE_URL=${URL:-https://s3-ap-northeast-1.amazonaws.com/aromajoin-downloads/software/aroma-http-controller/sample.war}
+
+  APP_FILE=${NAME:-sample.war}
+
+  DESTINATION_FILE=$HOME/$APP_FILE
 
   echo "Start downloading ${APP_FILE} from: ${APP_FILE_URL}"
 
diff --git a/install-jetty b/install-jetty
--- a/install-jetty
+++ b/install-jetty
@@ -1,19 +1,28 @@
 #!/bin/bash
 
+# Init option variables
+while getopts ":l:" opt; do
+  case $opt in
+    l)
+      URL=$OPTARG
+      echo "Download link: $URL" >&2
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
 JETTY_DOWNLOAD_URL=${URL:=http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.4.8.v20171121/jetty-distribution-9.4.8.v20171121.zip}
 JETTY_DESTINATION_FILE=/opt/jetty/jetty.zip
 
 main()
 {
-  # Init option variables
-  while getopts l: option
-  do
-  case "${option}"
-  in
-  l) URL=${OPTARG};;
-  esac
-  done
-
   # Check java version
   echo "Checking Java availability ..."
   javac -version
