[Update] enable hotspot script

diff --git a/src/enable-hotspot b/src/enable-hotspot
--- a/src/enable-hotspot
+++ b/src/enable-hotspot
@@ -1,60 +1,84 @@
 #!/bin/bash
 
-$HOSTAPD_CONFIG_FILE_PATH = /etc/hostapd/hostapd.conf
-$HOSTAPD_DEFAULT_CONFIG_PATH = /etc/default/hostapd
-$DNSMASQ_CONFIG_PATH = /etc/dnsmasq.conf
-$AUTO_HOTSPOT_SERVICE_PATH = /etc/systemd/system/autohotspot.service
-$AUTO_HOTSPOT_SCRIPT_PATH = /home/pi/rpizero-hotspot
+HOSTAPD_CONFIG_FILE_PATH=/etc/hostapd/hostapd.conf
+HOSTAPD_DEFAULT_CONFIG_PATH=/etc/default/hostapd
+DNSMASQ_CONFIG_PATH=/etc/dnsmasq.conf
+AUTO_HOTSPOT_SERVICE_PATH=/etc/systemd/system/autohotspot.service
+AUTO_HOTSPOT_SCRIPT_PATH=/home/pi/rpizero-hotspot
 
 hostapd_config()
 {
-  HOSTAPD_CONFIG = "interface=wlan0
-    driver=nl80211
-    ssid=asn1-hotspot
-    hw_mode=g
-    channel=6
-    wmm_enabled=0
-    macaddr_acl=0
-    auth_algs=1
-    ignore_broadcast_ssid=0
-    wpa=2
-    wpa_passphrase=1234567890
-    wpa_key_mgmt=WPA-PSK
-    wpa_pairwise=TKIP
-    rsn_pairwise=CCMP"
+  HOSTAPD_CONFIG="interface=wlan0
+  driver=nl80211
+  ssid=ASN1-HOTSPOT
+  hw_mode=g
+  channel=6
+  wmm_enabled=0
+  macaddr_acl=0
+  auth_algs=1
+  ignore_broadcast_ssid=0
+  wpa=2
+  wpa_passphrase=1234567890
+  wpa_key_mgmt=WPA-PSK
+  wpa_pairwise=TKIP
+  rsn_pairwise=CCMP"
 
+  echo -e "$HOSTAPD_CONFIG"
   echo -e "$HOSTAPD_CONFIG" > $HOSTAPD_CONFIG_FILE_PATH
 
   echo "DAEMON_CONF=\"/etc/hostapd/hostapd.conf\"" > $HOSTAPD_DEFAULT_CONFIG_PATH
+
+  if [ $? != 0 ]; then
+    echo "Failed to setup. Try it again."
+    exit 1
+  else
+    echo "Success."
+  fi
 }
 
 dnsmasq_config()
 {
-  DNSMASQ_CONFIG = "#AutoHotspot Config #stop DNSmasq from using resolv.conf
-    no-resolv 
-    #Interface to use 
-    interface=wlan0 
-    bind-interfaces 
-    dhcp-range=10.0.0.50,10.0.0.150,12h"
-
+  DNSMASQ_CONFIG="#AutoHotspot Config #stop DNSmasq from using resolv.conf
+  no-resolv
+  #Interface to use 
+  interface=wlan0 
+  bind-interfaces 
+  dhcp-range=10.0.0.50,10.0.0.150,12h"
+  echo -e "$DNSMASQ_CONFIG"
   echo -e "$DNSMASQ_CONFIG" > $DNSMASQ_CONFIG_PATH
+
+  if [ $? != 0 ]; then
+    echo "Failed to setup. Try it again."
+    exit 1
+  else
+    echo "Success."
+  fi
 }
 
 autohotspot_service()
 {
-  AUTO_HOTSPOT_SERVICE = "[Unit] Description=Automatically generates an internet Hotspot when a valid ssid is not in range 
-    After=multi-user.target
-    [Service]
-    Type=oneshot
-    RemainAfterExit=yes
-    ExecStart=$AUTO_HOTSPOT_SCRIPT_PATH
-    [Install]
-    WantedBy=multi-user.target"
-  
+  AUTO_HOTSPOT_SERVICE="[Unit]
+  Description=Automatically generates an internet Hotspot when a valid ssid is not in range 
+  After=multi-user.target
+  [Service]
+  Type=oneshot
+  RemainAfterExit=yes
+  ExecStart=$AUTO_HOTSPOT_SCRIPT_PATH
+  [Install]
+  WantedBy=multi-user.target"
+
+  echo -e "$AUTO_HOTSPOT_SERVICE"
   echo -e "$AUTO_HOTSPOT_SERVICE" > $AUTO_HOTSPOT_SERVICE_PATH
 
   echo "[Update] Enable auto-hotspot service..."
   systemctl enable autohotspot.service
+
+  if [ $? != 0 ]; then
+    echo "Failed to setup. Try it again."
+    exit 1
+  else
+    echo "Success."
+  fi
 }
 
 main()
@@ -81,5 +105,11 @@ main()
   echo "[Add] Autohotspot service..."
   autohotspot_service
 
+  echo "[Update] required software..."
+  apt-get purge dns-root-data
+  apt-get install iw
+
   echo "DONE."
 }
+
+main
