[Update] checking dnsmasq config content

diff --git a/src/rpi3-enable-hotspot b/src/rpi3-enable-hotspot
--- a/src/rpi3-enable-hotspot
+++ b/src/rpi3-enable-hotspot
@@ -60,23 +60,27 @@ dnsmasq_config()
   dhcp-range=10.0.0.50,10.0.0.150,12h"
   echo -e "$DNSMASQ_CONFIG"
 
-  echo "" >> $DNSMASQ_CONFIG_PATH
-  echo "#AutoHotspot Config" >> $DNSMASQ_CONFIG_PATH
-  echo "#stop DNSmasq from using resolv.conf" >> $DNSMASQ_CONFIG_PATH
-  echo "no-resolv" >> $DNSMASQ_CONFIG_PATH
-  echo "#Interface to use" >> $DNSMASQ_CONFIG_PATH
-  echo "interface=wlan0" >> $DNSMASQ_CONFIG_PATH
-  echo "bind-dynamic" >> $DNSMASQ_CONFIG_PATH
-  echo "server=8.8.8.8" >> $DNSMASQ_CONFIG_PATH
-  echo "domain-needed" >> $DNSMASQ_CONFIG_PATH
-  echo "bogus-priv" >> $DNSMASQ_CONFIG_PATH
-  echo "dhcp-range=10.0.0.50,10.0.0.150,12h" >> $DNSMASQ_CONFIG_PATH
-
-  if [ $? != 0 ]; then
-    echo "Failed to setup. Try it again."
-    exit 1
+  if grep -q '#AutoHotspot Config' $IP_FORWARDING_CONFIG_PATH; then
+    echo "Dnsmasq already setup."
   else
-    echo "Success."
+    echo "" >> $DNSMASQ_CONFIG_PATH
+    echo "#AutoHotspot Config" >> $DNSMASQ_CONFIG_PATH
+    echo "#stop DNSmasq from using resolv.conf" >> $DNSMASQ_CONFIG_PATH
+    echo "no-resolv" >> $DNSMASQ_CONFIG_PATH
+    echo "#Interface to use" >> $DNSMASQ_CONFIG_PATH
+    echo "interface=wlan0" >> $DNSMASQ_CONFIG_PATH
+    echo "bind-dynamic" >> $DNSMASQ_CONFIG_PATH
+    echo "server=8.8.8.8" >> $DNSMASQ_CONFIG_PATH
+    echo "domain-needed" >> $DNSMASQ_CONFIG_PATH
+    echo "bogus-priv" >> $DNSMASQ_CONFIG_PATH
+    echo "dhcp-range=10.0.0.50,10.0.0.150,12h" >> $DNSMASQ_CONFIG_PATH
+
+    if [ $? != 0 ]; then
+      echo "Failed to setup. Try it again."
+      exit 1
+    else
+      echo "Success."
+    fi
   fi
 }
 
@@ -168,6 +172,9 @@ main()
 
   echo "[Add] Dnsmasq configuration..."
   dnsmasq_config
+
+  echo "[Add] IP forwarding configuration..."
+  ip_forwarding
 
   echo "[Add] DHCPCD configuration..."
   dhcpcd_config
